version: '3.8'

services:
  app_prod:
    build: 
      context: .
      dockerfile: Dockerfile.prod
      target: ${STAGE:-testing}
    ports:
      - 8080:8080
    volumes:
      - .:/home/node/app
      - /home/node/app/dist
      - /home/node/app/node_modules